name = "SynapticFilter"
uuid = "0abcfceb-3f96-43f0-b19e-42926d139924"
authors = ["Simone Carlo Surace"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
